#! /bin/bash

OS=$(uname -o)

copy_os_specific_files() {
  local SRC="${HOME}/.config/yadm/${OS}" 
  if [ -d $SRC ]; then
     cp -r ${SRC}/. ${HOME}
  fi
}

case $OS in 
  "GNU/Linux")
    OS=Linux
    copy_os_specific_files()
    ;;
  "Android")
    OS=Android 
    copy_os_specific_files()
    ;;
  *)
    # .config/yadm/bootstrap.d/${OS}.sh
    echo Unsupported OS: $OS
    ;;
esac

