#! /bin/bash

OS=$(uname -o)

copy_os_specific_files() {
  local SRC="${HOME}/.config/yadm/${OS}" 
  if [ -d $SRC ]; then
     cp -r ${SRC}/. ${HOME}
  fi
}

setup_linux() {
  sudo apt update
  sudo apt install -y bash-completion curl fzf git git-lfs gnupg htop jq luarocks mosh ncdu rsync tmux ufw unzip zip 
  curl https://get.volta.sh | bash
  curl -LsSf https://astral.sh/uv/install.sh | sh
}

setup_android() {
  apt update
  apt install curl fzf git git-lfs gnupg htop jq luarocks mosh neovim rsync tmux uv unzip zip
}

case $OS in 
  "GNU/Linux")
    OS=Linux
    copy_os_specific_files
    setup_linux
    ;;
  "Android")
    OS=Android 
    copy_os_specific_files
    ;;
  *)
    # .config/yadm/bootstrap.d/${OS}.sh
    echo Unsupported OS: $OS
    ;;
esac

