set -Fg @fg "#{?pane_in_mode,#{@copy-accent},#{@accent}}"
set -Fg @bg "#{?pane_in_mode,#{@copy-ink},#{@ink}}"
set -Fg status-style "fg=#{?pane_in_mode,#{@copy-accent},#{@accent}},bg=#{?pane_in_mode,#{@copy-ink},#{@ink}}"
set -Fg mode-style "fg=#{@copy-ink},bg=#{@copy-accent},bold"
