if -F "#{m:*RGB*,#{client_termfeatures}}" {
  set -g @palette "rgb"
  set -g @accent "#c8d3f5"
  set -g @ink "#222436"
  set -g @copy-accent "#ff966c"
  set -g @copy-ink "#1b1d2b"
} {
  if -F "#{m:*256color*,#{client_termname}}" {
    set -g @palette "256"
    set -g @accent "colour189"
    set -g @ink "colour235"
    set -g @copy-accent "colour209"
    set -g @copy-ink "colour234"
  } {
    set -g @palette "normal"
    set -g @accent "white"
    set -g @ink "black"
    set -g @copy-accent "yellow"
    set -g @copy-ink "black"
  }
}

source-file ~/.tmux.d/status.conf
